# Generated by Django 5.1.7 on 2025-04-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image_delete_recipetag_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='is_optional',
        ),
    ]
