# Generated by Django 5.1.7 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
